### ISSUE TITLE
Can't install mapnik2 via pip install

### ISSUE THREAD

**Issue by rapadu** [mapnik/pymapnik2#7]
I can't load mapnik2 from pip. 
I get the following error. 

```
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-snc_7_7f/mapnik2/setup.py", line 10
        exec open('src/mapnik/utils.py').read() in mapnik_utils
                ^
    SyntaxError: invalid syntax
```

Anyone with this problem?

**Comment by filtoid** [comment]
+1 for this problem. Not sure of a solution

**Comment by goDeni** [comment]
+1 same problem
